export type PlaneInfo = {
  hex: string
  type: 'adsb_icao'|'adsb_icao_nt'|'mlat'|'mode_s'
  flight?: string
  r?: string
  t?: string
  desc?: string
  alt_baro?: number|'ground'
  alt_geom?: number
  gs?: number
  ias?: number
  tas?: number
  mach?: number
  track?: number
  track_rate?: number
  roll?: number
  mag_heading?: number
  true_heading?: number
  baro_rate?: number
  geom_rate?: number
  squawk?: string
  emergency?: string
  category?: string
  nav_qnh?: number
  nav_altitude_mcp?: number
  nav_altitude_fms?: number
  nav_heading?: number
  lat: number
  lon: number
  nic: number
  rc: number
  seen_pos: number
  version?: number
  nic_baro?: number
  nac_p?: number
  nac_v?: number
  sil?: number
  sil_type?: string
  gva?: number
  sda?: number
  alert?: number
  spi?: number
  mlat: string[]
  tisb: string[]
  messages: number
  seen: number
  rssi: number
  dst: number
  dir: number
  wd?: number
  ws?: number
  oat?: number
  tat?: number
  ownOp?: string
  year?: string
  dbFlags?: number
  nav_modes?: string[]
  calc_track?: number
}

export type AirplanesDotLive = {
  ac: PlaneInfo[]
  msg: string
  now: number
  total: number
  ctime: number
  ptime: number
}